### ISSUE TITLE
Is there a installation package(APK)?Gradle environment does not match。thanks

### ISSUE THREAD

**Issue by 13120241790** [klinker24/Android-SlidingEmojiKeyboard#1]
Error:Unable to load class 'org.codehaus.groovy.runtime.StringGroovyMethods'.
Possible causes for this unexpected error include:<ul><li>You are using JDK version 'java version "1.7.0_79"'. Some versions of JDK 1.7 (e.g. 1.7.0_10) may cause class loading errors in Gradle.
Please update to a newer version (e.g. 1.7.0_67).
<a href="open.project.structure">Open JDK Settings</a></li><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

---

**Comment by klinker24** [comment]
No clue what the error is for you, but they are on the play store: 

https://play.google.com/store/apps/details?id=com.klinker.android.emoji_keyboard_trial&hl=en

https://play.google.com/store/apps/details?id=com.klinker.android.emoji_keyboard_trial_ios&hl=en
