### ISSUE TITLE
Null point are exception

### ISSUE THREAD

**Issue by ziddikhattak** [klinker24/Android-SlidingEmojiKeyboard#12]
in log:android monitor  
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getString(int)' on a null object reference

this error throws me to following line of code in mian activity... i dont know how to resolve... please guide me.

public static final String CHANGE_ICON_SET_KEY = EmojiKeyboardService.getStaticApplicationContext()
            .getString(R.string.setting_change_icon_set_key);

**Comment by klinker24** [comment]
This is the same as #11
