### ISSUE TITLE
Black Symbol

### ISSUE THREAD

**Issue by monowar1993** [klinker24/Android-SlidingEmojiKeyboard#2]
A black symbol occurs when i press backspace for almost every emoji. I am not getting a way to fix it.

**Comment by klinker24** [comment]
It is because some emojis take up 2 unicode characters, while others are just one. Our delete button always just removes one character. 

I honestly do not know the best way to go about solving this. Feel free to make a suggestion or implement one with a pull request and I would take a look.

**Comment by monowar1993** [comment]
Yes I came up with something. Still need a few thing to finish it up. Hope I can provide you the solution tomorrow morning. I need a little help. Can you suggest me a way so that I can use stickers also with emojis. It will be a real help. Thanks.

**Comment by klinker24** [comment]
Sorry but I am confused what you mean, like the sticker images that facebook has? I would suggest looking into ImageSpans. This is really a completely different thing than emojis. Emojis are defined, unicode symbols, that are standardized, stickers are just images that are placed alongside text.

**Comment by monowar1993** [comment]
yes like facebook. But when I'll be sending stickers using a keyboard its send the stickers as a picture attachment. I would like to know how can I handle that. Clicking a picture and it will be automatically added as an attachment.

**Comment by monowar1993** [comment]
private StringBuilder composing = new StringBuilder();
private void removeText() {
        final int length = composing.length();
        if (length > 1) {
            composing.delete(length - 1, length);
            getCurrentInputConnection().setComposingText(composing, 1);
            //updateCandidates();
        } else if (length > 0) {
            composing.setLength(0);
            getCurrentInputConnection().commitText("", 0);
            //updateCandidates();
        } else {
            keyDownUp(KeyEvent.KEYCODE_DEL);
        }
        //updateShiftKeyState(getCurrentInputEditorInfo());
    }

this could help deleting an emoji with a single backspace.

**Comment by klinker24** [comment]
I pretty sure you will have to build something into the app for that, you won't be able to serve pictures like that through a keyboard.

Thanks for the code, will look at it further when I get some time

**Comment by monowar1993** [comment]
I will have to send by attaching image.

**Comment by flide** [comment]
This is fixed as part of my pull request. now delete button removes the whole emoji.
