### ISSUE TITLE
Why not release on app stores?

### ISSUE THREAD

**Issue by flide** [klinker24/Android-SlidingEmojiKeyboard#6]
As I read from the readme file, you have decided not to release this to app stores. Any particular reason?

If you want I can fix the "unlocker" part, which I ripped.

**Comment by klinker24** [comment]
I am not going to, sorry. The specific android and ios keyboards are used in my Talon for Twitter and EvolveSMS apps as add-on packages. Downloading that specific version will give you those emojis. That isn't functionality that I want to change.
